# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ldominiq <marvin@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/08/23 18:03:27 by ldominiq          #+#    #+#              #
#    Updated: 2021/08/24 15:08:56 by ldominiq         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#include "includes/ft.h"

SRC = ft_putchar.c ft_swap.c ft_putstr.c ft_strlen.c ft_strcmp.c

PRE = ./srcs/
all:

clean:
	rm *.o

fclean:

re:

libft.a:

